# Stage 1: Build
FROM eclipse-temurin:21-jdk-jammy AS build
WORKDIR /app
ARG SERVICE_NAME

# Copy Infrastructure
COPY .mvn .mvn
COPY mvnw .
RUN chmod +x mvnw

# Copy the Service
COPY ${SERVICE_NAME}/pom.xml ./pom.xml
COPY ${SERVICE_NAME}/src ./src

# Build
RUN ./mvnw clean package -DskipTests

# Stage 2: Runtime
FROM eclipse-temurin:21-jre-jammy
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75.0", "-jar", "app.jar"]
