spring:
  application:
    name: order-service

  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:order_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2

  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      catalog-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15000ms
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 80

resilience4j.retry:
  configs:
    default:
      consume-attributes: true # ensures that the retry doesn't happen if the circuit is already OPEN

  instances:
    catalog-service:
      maxAttempts: 3
      waitDuration: 500ms
      retryExceptions:
        - java.io.IOException
        - feign.RetryableException

eureka:
  client:
    healthcheck:
      enabled: true

    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}

  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

server:
  port: ${SERVER_PORT:5002}
