spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-service-route
              uri: lb://IDENTITY-SERVICE
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=0

            - id: catalog-service-route
              uri: lb://CATALOG-SERVICE
              predicates:
                - Path=/api/v1/categories/**, /api/v1/books/**
              filters:
                - StripPrefix=0

            - id: order-service-route
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - StripPrefix=0

eureka:
  client:
    healthcheck:
      enabled: true

    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}

  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

jwt:
  secret: ${JWT_SECRET:1zuATy0nfdvrFa3Zmkc+HX9HFA7ARqZn6yy3qejeluE=}

server:
  port: ${SERVER_PORT:8080}
